/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeShowcaseRouteImport } from './routes/theme-showcase'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles/index'
import { Route as StopsIndexRouteImport } from './routes/stops/index'
import { Route as SavedIndexRouteImport } from './routes/saved/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SavedRecentRouteImport } from './routes/saved/recent'
import { Route as RoutesRouteIdRouteImport } from './routes/routes/$routeId'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as FeedReportIdRouteImport } from './routes/feed/$reportId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminVehiclesRouteImport } from './routes/admin/vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStopsRouteImport } from './routes/admin/stops'
import { Route as AdminRoutesRouteImport } from './routes/admin/routes'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminBulkUploadRouteImport } from './routes/admin/bulk-upload'
import { Route as RoutesRouteIdForumRouteImport } from './routes/routes/$routeId/forum'
import { Route as RoutesRouteIdForumMembersRouteImport } from './routes/routes/$routeId/forum/members'
import { Route as RoutesRouteIdForumPostsPostIdRouteImport } from './routes/routes/$routeId/forum/posts/$postId'

const ThemeShowcaseRoute = ThemeShowcaseRouteImport.update({
  id: '/theme-showcase',
  path: '/theme-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsIndexRoute = StopsIndexRouteImport.update({
  id: '/stops/',
  path: '/stops/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRecentRoute = SavedRecentRouteImport.update({
  id: '/saved/recent',
  path: '/saved/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedReportIdRoute = FeedReportIdRouteImport.update({
  id: '/feed/$reportId',
  path: '/feed/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStopsRoute = AdminStopsRouteImport.update({
  id: '/admin/stops',
  path: '/admin/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/admin/routes',
  path: '/admin/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkUploadRoute = AdminBulkUploadRouteImport.update({
  id: '/admin/bulk-upload',
  path: '/admin/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdForumRoute = RoutesRouteIdForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => RoutesRouteIdRoute,
} as any)
const RoutesRouteIdForumMembersRoute =
  RoutesRouteIdForumMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => RoutesRouteIdForumRoute,
  } as any)
const RoutesRouteIdForumPostsPostIdRoute =
  RoutesRouteIdForumPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => RoutesRouteIdForumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/theme-showcase': typeof ThemeShowcaseRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRouteWithChildren
  '/saved/recent': typeof SavedRecentRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/feed': typeof FeedIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/saved': typeof SavedIndexRoute
  '/stops': typeof StopsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/routes/$routeId/forum': typeof RoutesRouteIdForumRouteWithChildren
  '/routes/$routeId/forum/members': typeof RoutesRouteIdForumMembersRoute
  '/routes/$routeId/forum/posts/$postId': typeof RoutesRouteIdForumPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/theme-showcase': typeof ThemeShowcaseRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRouteWithChildren
  '/saved/recent': typeof SavedRecentRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/feed': typeof FeedIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/saved': typeof SavedIndexRoute
  '/stops': typeof StopsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/routes/$routeId/forum': typeof RoutesRouteIdForumRouteWithChildren
  '/routes/$routeId/forum/members': typeof RoutesRouteIdForumMembersRoute
  '/routes/$routeId/forum/posts/$postId': typeof RoutesRouteIdForumPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/theme-showcase': typeof ThemeShowcaseRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRouteWithChildren
  '/saved/recent': typeof SavedRecentRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/stops/': typeof StopsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/routes/$routeId/forum': typeof RoutesRouteIdForumRouteWithChildren
  '/routes/$routeId/forum/members': typeof RoutesRouteIdForumMembersRoute
  '/routes/$routeId/forum/posts/$postId': typeof RoutesRouteIdForumPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/theme-showcase'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/routes/$routeId'
    | '/saved/recent'
    | '/admin'
    | '/chat'
    | '/feed'
    | '/leaderboard'
    | '/reports'
    | '/routes'
    | '/saved'
    | '/stops'
    | '/vehicles'
    | '/routes/$routeId/forum'
    | '/routes/$routeId/forum/members'
    | '/routes/$routeId/forum/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/theme-showcase'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/routes/$routeId'
    | '/saved/recent'
    | '/admin'
    | '/chat'
    | '/feed'
    | '/leaderboard'
    | '/reports'
    | '/routes'
    | '/saved'
    | '/stops'
    | '/vehicles'
    | '/routes/$routeId/forum'
    | '/routes/$routeId/forum/members'
    | '/routes/$routeId/forum/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/theme-showcase'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/routes/$routeId'
    | '/saved/recent'
    | '/admin/'
    | '/chat/'
    | '/feed/'
    | '/leaderboard/'
    | '/reports/'
    | '/routes/'
    | '/saved/'
    | '/stops/'
    | '/vehicles/'
    | '/routes/$routeId/forum'
    | '/routes/$routeId/forum/members'
    | '/routes/$routeId/forum/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ThemeShowcaseRoute: typeof ThemeShowcaseRoute
  AdminBulkUploadRoute: typeof AdminBulkUploadRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminStopsRoute: typeof AdminStopsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  FeedReportIdRoute: typeof FeedReportIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRouteWithChildren
  SavedRecentRoute: typeof SavedRecentRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  SavedIndexRoute: typeof SavedIndexRoute
  StopsIndexRoute: typeof StopsIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-showcase': {
      id: '/theme-showcase'
      path: '/theme-showcase'
      fullPath: '/theme-showcase'
      preLoaderRoute: typeof ThemeShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/': {
      id: '/stops/'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/recent': {
      id: '/saved/recent'
      path: '/saved/recent'
      fullPath: '/saved/recent'
      preLoaderRoute: typeof SavedRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$reportId': {
      id: '/feed/$reportId'
      path: '/feed/$reportId'
      fullPath: '/feed/$reportId'
      preLoaderRoute: typeof FeedReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stops': {
      id: '/admin/stops'
      path: '/admin/stops'
      fullPath: '/admin/stops'
      preLoaderRoute: typeof AdminStopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-upload': {
      id: '/admin/bulk-upload'
      path: '/admin/bulk-upload'
      fullPath: '/admin/bulk-upload'
      preLoaderRoute: typeof AdminBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId/forum': {
      id: '/routes/$routeId/forum'
      path: '/forum'
      fullPath: '/routes/$routeId/forum'
      preLoaderRoute: typeof RoutesRouteIdForumRouteImport
      parentRoute: typeof RoutesRouteIdRoute
    }
    '/routes/$routeId/forum/members': {
      id: '/routes/$routeId/forum/members'
      path: '/members'
      fullPath: '/routes/$routeId/forum/members'
      preLoaderRoute: typeof RoutesRouteIdForumMembersRouteImport
      parentRoute: typeof RoutesRouteIdForumRoute
    }
    '/routes/$routeId/forum/posts/$postId': {
      id: '/routes/$routeId/forum/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/routes/$routeId/forum/posts/$postId'
      preLoaderRoute: typeof RoutesRouteIdForumPostsPostIdRouteImport
      parentRoute: typeof RoutesRouteIdForumRoute
    }
  }
}

interface RoutesRouteIdForumRouteChildren {
  RoutesRouteIdForumMembersRoute: typeof RoutesRouteIdForumMembersRoute
  RoutesRouteIdForumPostsPostIdRoute: typeof RoutesRouteIdForumPostsPostIdRoute
}

const RoutesRouteIdForumRouteChildren: RoutesRouteIdForumRouteChildren = {
  RoutesRouteIdForumMembersRoute: RoutesRouteIdForumMembersRoute,
  RoutesRouteIdForumPostsPostIdRoute: RoutesRouteIdForumPostsPostIdRoute,
}

const RoutesRouteIdForumRouteWithChildren =
  RoutesRouteIdForumRoute._addFileChildren(RoutesRouteIdForumRouteChildren)

interface RoutesRouteIdRouteChildren {
  RoutesRouteIdForumRoute: typeof RoutesRouteIdForumRouteWithChildren
}

const RoutesRouteIdRouteChildren: RoutesRouteIdRouteChildren = {
  RoutesRouteIdForumRoute: RoutesRouteIdForumRouteWithChildren,
}

const RoutesRouteIdRouteWithChildren = RoutesRouteIdRoute._addFileChildren(
  RoutesRouteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ThemeShowcaseRoute: ThemeShowcaseRoute,
  AdminBulkUploadRoute: AdminBulkUploadRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminStopsRoute: AdminStopsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  FeedReportIdRoute: FeedReportIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRouteWithChildren,
  SavedRecentRoute: SavedRecentRoute,
  AdminIndexRoute: AdminIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  SavedIndexRoute: SavedIndexRoute,
  StopsIndexRoute: StopsIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
