/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles/index'
import { Route as StopsIndexRouteImport } from './routes/stops/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as FeedIndexRouteImport } from './routes/feed/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoutesRouteIdRouteImport } from './routes/routes/$routeId'
import { Route as ReportsNewRouteImport } from './routes/reports/new'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as FeedReportIdRouteImport } from './routes/feed/$reportId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminVehiclesRouteImport } from './routes/admin/vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStopsRouteImport } from './routes/admin/stops'
import { Route as AdminRoutesRouteImport } from './routes/admin/routes'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminBulkUploadRouteImport } from './routes/admin/bulk-upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsIndexRoute = StopsIndexRouteImport.update({
  id: '/stops/',
  path: '/stops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedReportIdRoute = FeedReportIdRouteImport.update({
  id: '/feed/$reportId',
  path: '/feed/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStopsRoute = AdminStopsRouteImport.update({
  id: '/admin/stops',
  path: '/admin/stops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/admin/routes',
  path: '/admin/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkUploadRoute = AdminBulkUploadRouteImport.update({
  id: '/admin/bulk-upload',
  path: '/admin/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin': typeof AdminIndexRoute
  '/feed': typeof FeedIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/stops': typeof StopsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin': typeof AdminIndexRoute
  '/feed': typeof FeedIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/stops': typeof StopsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/bulk-upload': typeof AdminBulkUploadRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/admin/stops': typeof AdminStopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feed/$reportId': typeof FeedReportIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/admin/': typeof AdminIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/stops/': typeof StopsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/register'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/reports/new'
    | '/routes/$routeId'
    | '/admin'
    | '/feed'
    | '/leaderboard'
    | '/reports'
    | '/stops'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/register'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/reports/new'
    | '/routes/$routeId'
    | '/admin'
    | '/feed'
    | '/leaderboard'
    | '/reports'
    | '/stops'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/admin/bulk-upload'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/stops'
    | '/admin/users'
    | '/admin/vehicles'
    | '/auth/login'
    | '/auth/register'
    | '/feed/$reportId'
    | '/profile/$userId'
    | '/reports/new'
    | '/routes/$routeId'
    | '/admin/'
    | '/feed/'
    | '/leaderboard/'
    | '/reports/'
    | '/stops/'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminBulkUploadRoute: typeof AdminBulkUploadRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AdminStopsRoute: typeof AdminStopsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  FeedReportIdRoute: typeof FeedReportIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ReportsNewRoute: typeof ReportsNewRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  StopsIndexRoute: typeof StopsIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/': {
      id: '/stops/'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$reportId': {
      id: '/feed/$reportId'
      path: '/feed/$reportId'
      fullPath: '/feed/$reportId'
      preLoaderRoute: typeof FeedReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stops': {
      id: '/admin/stops'
      path: '/admin/stops'
      fullPath: '/admin/stops'
      preLoaderRoute: typeof AdminStopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-upload': {
      id: '/admin/bulk-upload'
      path: '/admin/bulk-upload'
      fullPath: '/admin/bulk-upload'
      preLoaderRoute: typeof AdminBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminBulkUploadRoute: AdminBulkUploadRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AdminStopsRoute: AdminStopsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  FeedReportIdRoute: FeedReportIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ReportsNewRoute: ReportsNewRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  StopsIndexRoute: StopsIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
